### ISSUE TITLE
Should the library warn against using emoji in alt text?

### ISSUE THREAD

**Issue by katydecorah** [double-great/alt-text#42]
To do:

- [ ] Learn: What does emoji sound like to a screen reader?

**Comment by jsnmrs** [comment]
I saw this related presentation in my feed: [https://www.youtube.com/watch?v=uIbPcZq6izk](https://www.youtube.com/watch?v=uIbPcZq6izk)

Skimming, it seems like there are variances between emoji descriptions by platform — sending an unintended message seems very possible.

**Comment by katydecorah** [comment]
Fixed in #42
